version: '3.8'

services:
  
  db:
    container_name: ${DB_NAME}
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    restart: always
    env_file:
      - .env 

  
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:80"
    restart: always
    env_file:
      - .env 

  
  my-app:
    depends_on:
      - db
    image: server
    ports:
      - "3000:3000"
    restart: always

volumes:
  db_data: